on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - master
      - test-action
name: fix-lint
jobs:
  fix-lint:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install --engine-strict
      - run: npm run fix
      - uses: chingor13/code-suggester@review-action # takes the changes from git directory
        with:
          command: review
          pull_number: ${{ github.event.pull_request.number }}